before_script:
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s) 
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - deploy_dev
  - deploy_staging
  - deploy_main

Deploy Main:
  stage: deploy_main
  script:
    - git remote add production $production_remote_url
    - "git checkout -b gh-main"
    - "git push production gh-main -f"
  only:
    - main

Deploy Staging:
  stage: deploy_staging
  script:
    - git remote add stagingremote $staging_remote_url
    - "git checkout -b gh-staging"
    - "git push stagingremote gh-staging -f"
  only:
    - staging

Deploy Dev:
  stage: deploy_dev
  script:
    - git remote add devremote $dev_remote_url
    - "git checkout -b gh-dev"
    - "git push devremote gh-dev -f"
  only:
    - dev
